// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "Hedgehog":
            case "anim1":return [img`
..............................
..............................
..............................
..............................
..............................
..........fffffffff...........
.........ff9f9f9f9ff..........
........ff999999999f..........
........f9999999999f..........
........ff99fddddddf..........
........f99fdddddfdf..........
........ff9fdddddfdfff........
........f99fdddddddd3f........
........ff99ffdddddfdf........
........f99999ffffffff........
........ff9999fdf9f...........
........f9ffffdddffff.........
........fffddfdddfddf.........
........f9fddfdddfddf.........
........fffddfdddfddf.........
........f9ffffdddffff.........
........ff9999fdf9f...........
........ff99999f99f...........
.........ffddffddff...........
..........fddffddf............
..........fddffddf............
..........ffffffff............
..............................
..............................
..............................
`, img`
..............................
..............................
..............................
..............................
..............................
..........fffffffff...........
.........ff9f9f9f9ff..........
........ff999999999f..........
........f9999999999f..........
........ff99fddddddf..........
........f99fdddddfdf..........
........ff9fdddddfdfff........
........f99fdddddddd3f........
........ff99ffdddddfdf........
........f99999ffffffff........
........ff999ffdf9f...........
........f9ffffdddfffff........
........fffdddfddfdddf........
........f9fdddfddfdddf........
........fffffffddfffff........
........f9999fdddff...........
........ff9999fdf9f...........
........ff99999f99f...........
.........ffddffddff...........
..........fddffddf............
..........fddffddf............
..........fffffddf............
..............fddf............
..............ffff............
..............................
`, img`
..............................
..............................
..............................
..............................
..............................
..........fffffffff...........
.........ff9f9f9f9ff..........
........ff999999999f..........
........f9999999999f..........
........ff99fddddddf..........
........f99fdddddfdf..........
........ff9fdddddfdfff........
........f99fdddddddd3f........
........ff99ffdddddfdf........
........f99999ffffffff........
........ff999ffdf9f...........
........f9ffffdddfffff........
........fffdddfddfdddf........
........f9fdddfddfdddf........
........fffffffddfffff........
........f9999fdddff...........
........ff9999fdf9f...........
........ff99999f99f...........
.........ffddffddff...........
..........fddffddf............
..........fddffddf............
..........fddfffff............
..........fddf................
..........ffff................
..............................
`];
        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
