info.setLife(3)
scene.setBackgroundImage(assets.image`temp background`)
controller.moveSprite(sprites.create(assets.image`Hedgehogmaincharacter`, SpriteKind.Player))
music.play(music.createSong(assets.song`Song`), music.PlaybackMode.UntilDone)
sprites.create(assets.image`myImage`, SpriteKind.Enemy).setPosition(164, 84)
sprites.create(assets.image`myImage`, SpriteKind.Enemy).setVelocity(26, 10)
