controller.A.onEvent(ControllerButtonEvent.Released, function () {
	
})
controller.player1.moveSprite(sprites.create(img`
    ..............................
    ..............................
    ..............................
    ..............................
    ..........fffffffff...........
    .........ff9f9f9f9ff..........
    ........ff999999999f..........
    ........f9999999999f..........
    ........ff99fddddddf..........
    ........f99fdddddfdf..........
    ........ff9fdddddfdfff........
    ........f99fdddddddd3f........
    ........ff99ffdddddfdf........
    ........f99999ffffffff........
    ........ff9999fdf9f...........
    ........f9ffffdddffff.........
    ........fffddfdddfddf.........
    ........f9fddfdddfddf.........
    ........fffddfdddfddf.........
    ........f9ffffdddffff.........
    ........ff9999fdf9f...........
    ........ff99999f99f...........
    .........ffddffddff...........
    ..........fddffddf............
    ..........fddffddf............
    ..........ffffffff............
    ..............................
    ..............................
    ..............................
    ..............................
    `, SpriteKind.Player))
music.play(music.createSong(hex`00780004080200`), music.PlaybackMode.UntilDone)
